# Generated by Django 5.1.5 on 2025-02-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="settings",
        ),
    ]
