# Generated by Django 5.1.5 on 2025-01-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="settings",
            field=models.JSONField(null=True),
        ),
    ]
