# Generated by Django 5.1.5 on 2025-01-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_agent_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="settings",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
