# Generated by Django 5.1.5 on 2025-02-05 00:03

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_alter_agent_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="settings",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
