# Generated by Django 5.1.5 on 2025-02-05 21:55

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="data",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="data_schema",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="output",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="output_schema",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
