version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - ./docker/volumes/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
