version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - ./docker/volumes/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
      POSTGRES_DB: archane
    ports:
      - "5432:5432"
