# Generated by Django 5.1.5 on 2025-01-31 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("goal_generation", "0002_alter_goalgeneration_system_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalgeneration",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agents.agent",
            ),
        ),
    ]
