# Generated by Django 5.1.5 on 2025-01-31 21:53

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goal_generation", "0003_goalgeneration_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalgeneration",
            name="system_prompt",
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
