# Generated by Django 5.1.5 on 2025-02-05 00:03

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goal_generation", "0004_alter_goalgeneration_system_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalgeneration",
            name="data",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
