# Generated by Django 5.1.5 on 2025-02-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goal_generation", "0006_goalgeneration_output"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goalgeneration",
            name="output",
        ),
    ]
