# Generated by Django 5.1.5 on 2025-02-05 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_alter_agent_settings"),
        ("goal_generation", "0008_goalgeneration_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalgeneration",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modules",
                to="agents.agent",
            ),
        ),
    ]
