# Generated by Django 5.1.5 on 2025-02-05 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_module"),
        ("goal_generation", "0009_alter_goalgeneration_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goalgeneration",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="goalgeneration",
            name="id",
        ),
        migrations.RemoveField(
            model_name="goalgeneration",
            name="name",
        ),
        migrations.AddField(
            model_name="goalgeneration",
            name="module_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="agents.module",
            ),
            preserve_default=False,
        ),
    ]
