# Generated by Django 5.1.5 on 2025-02-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "goal_generation",
            "0010_remove_goalgeneration_agent_remove_goalgeneration_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goalgeneration",
            name="data",
        ),
        migrations.RemoveField(
            model_name="goalgeneration",
            name="output",
        ),
    ]
