# Generated by Django 3.1.12 on 2025-01-24 22:28

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', djongo.models.fields.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
