# Generated by Django 3.1.12 on 2025-01-24 21:33

from django.db import migrations, models
import djongo.models.fields
import state.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', djongo.models.fields.JSONField()),
                ('interests', djongo.models.fields.ArrayField(blank=True, model_container=state.models.Interest)),
                ('locations', djongo.models.fields.ArrayField(blank=True, model_container=state.models.Interest)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
