# Generated by Django 3.1.12 on 2025-01-24 22:35

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetaudience',
            name='age_range',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
