# Generated by Django 3.1.12 on 2025-01-24 22:38

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20250124_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetaudience',
            name='age_range',
            field=djongo.models.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
