# Generated by Django 3.1.12 on 2025-01-24 22:43

from django.db import migrations, models
import djongo.models.fields
import state.models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_auto_20250124_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetaudience',
            name='interests',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=state.models.Interest, null=True),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='age_range',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
