# Generated by Django 5.1.5 on 2025-02-12 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Module Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funcname",
                    models.CharField(
                        choices=[
                            ("chat openai like", "Chat openai like"),
                            ("tanti saluti", "Tanti saluti"),
                            ("print", "Print"),
                        ],
                        max_length=50,
                        verbose_name="Function Name",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "input_schema",
                    models.JSONField(default=dict, verbose_name="Input Schema"),
                ),
                (
                    "output_schema",
                    models.JSONField(default=dict, verbose_name="Output Schema"),
                ),
                (
                    "config_schema",
                    models.JSONField(default=dict, verbose_name="Config Schema"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("funcname", "name")},
            },
        ),
        migrations.CreateModel(
            name="ModuleAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Config"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordine di esecuzione del comando nel contesto del modulo",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_actions",
                        to="modules.action",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_actions",
                        to="modules.module",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "inputs",
                    models.JSONField(blank=True, null=True, verbose_name="Inputs"),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Config"
                    ),
                ),
                (
                    "output",
                    models.JSONField(blank=True, null=True, verbose_name="Output"),
                ),
                (
                    "module_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="modules.moduleaction",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="moduleaction",
            constraint=models.UniqueConstraint(
                fields=("module", "action"), name="unique_module_action"
            ),
        ),
    ]
