# Generated by Django 5.1.5 on 2025-02-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="config_schema",
            field=models.JSONField(blank=True, null=True, verbose_name="Config Schema"),
        ),
        migrations.AlterField(
            model_name="action",
            name="input_schema",
            field=models.JSONField(blank=True, null=True, verbose_name="Input Schema"),
        ),
        migrations.AlterField(
            model_name="action",
            name="output_schema",
            field=models.JSONField(blank=True, null=True, verbose_name="Output Schema"),
        ),
    ]
