# Generated by Django 5.1.5 on 2025-02-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "modules",
            "0002_alter_action_config_schema_alter_action_input_schema_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moduleaction",
            name="input",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Input"
            ),
        ),
        migrations.AddField(
            model_name="moduleaction",
            name="output",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Output"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="funcname",
            field=models.CharField(
                choices=[
                    ("chat openai like", "Chat openai like"),
                    ("print", "Print"),
                    ("tanti saluti", "Tanti saluti"),
                ],
                max_length=50,
                verbose_name="Function Name",
            ),
        ),
    ]
