# Generated by Django 5.1.5 on 2025-02-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0004_remove_moduleaction_output"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moduleaction",
            old_name="config",
            new_name="configs",
        ),
        migrations.RenameField(
            model_name="moduleaction",
            old_name="input",
            new_name="inputs",
        ),
    ]
