# Generated by Django 5.1.5 on 2025-02-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0005_rename_config_moduleaction_configs_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="execution",
            old_name="config",
            new_name="configs",
        ),
    ]
