# Generated by Django 5.1.5 on 2025-02-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0006_rename_config_execution_configs"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="moduleaction",
            name="unique_module_action",
        ),
    ]
