# Generated by Django 5.1.5 on 2025-02-12 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("modules", "0007_remove_moduleaction_unique_module_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moduleaction",
            options={},
        ),
        migrations.AddField(
            model_name="module",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modules",
                to="agents.agent",
            ),
        ),
    ]
