# Generated by Django 5.1.5 on 2025-02-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("modules", "0008_alter_moduleaction_options_module_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="agent",
        ),
        migrations.AddField(
            model_name="module",
            name="agents",
            field=models.ManyToManyField(
                blank=True, related_name="modules", to="agents.agent"
            ),
        ),
    ]
