# Generated by Django 5.1.5 on 2025-02-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0009_remove_module_agent_module_agents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleaction",
            name="action",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="module_actions",
                to="modules.action",
            ),
        ),
        migrations.AlterField(
            model_name="moduleaction",
            name="module",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="module_actions",
                to="modules.module",
            ),
        ),
    ]
