# Generated by Django 5.1.5 on 2025-02-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0010_alter_moduleaction_action_alter_moduleaction_module"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moduleaction",
            name="inputs",
        ),
        migrations.AlterField(
            model_name="action",
            name="funcname",
            field=models.CharField(
                choices=[("llm_openai_like", "Llm openai like"), ("print", "Print")],
                max_length=50,
                verbose_name="Function Name",
            ),
        ),
    ]
