# Generated by Django 5.1.5 on 2025-02-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0011_remove_moduleaction_inputs_alter_action_funcname"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduleaction",
            name="inputs",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Input"
            ),
        ),
    ]
