# Generated by Django 5.1.5 on 2025-02-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0012_moduleaction_inputs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moduleaction",
            name="order",
        ),
    ]
