# Generated by Django 5.1.5 on 2025-02-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("schema", models.JSONField(blank=True, default=dict, null=True)),
                ("data", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "agents",
                    models.ManyToManyField(
                        blank=True, related_name="memories", to="agents.agent"
                    ),
                ),
            ],
        ),
    ]
