# Generated by Django 5.1.5 on 2025-02-23 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("memories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memory",
            options={"verbose_name_plural": "Memories"},
        ),
        migrations.RemoveField(
            model_name="memory",
            name="agents",
        ),
        migrations.AddField(
            model_name="memory",
            name="agents",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memories",
                to="agents.agent",
            ),
        ),
    ]
