# Generated by Django 5.1.5 on 2025-02-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0002_alter_memory_options_remove_memory_agents_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memory",
            old_name="agents",
            new_name="agent",
        ),
    ]
